[build]
  command = "npm run build"  # Adjust based on your project's build command
  publish = "dist"  # Adjust based on your output directory

[context.production]
  command = "npm run build:prod"  # Custom build command for production

[context.deploy-preview]
  command = "npm run build:staging"  # Custom build command for preview deployments

[[redirects]]

from="/*"
to="/index.html"
status=200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    
