[build]
  command = "npm run build"  # Adjust based on your project's build command
  publish = "dist"  # Adjust based on your output directory

[context.production]
  command = "npm run build"  # Updated to use existing build script

[context.deploy-preview]
  command = "npm run build"  # Updated to match available scripts

[[redirects]]
from="/*"
to="/index.html"
status=200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    
